version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -q -r lambda.zip .
artifacts:
  files:
    - lambda.zip
